

USE `gq36vb3sbd3kklm4`;

CREATE TABLE burger (
    id INT AUTO_INCREMENT NOT NULL,
    choice TEXT NOT NULL,
    devoured BOOLEAN DEFAULT false,
	createdAt TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
    PRIMARY KEY(id)
);